version: "3"
services:
  api:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mysql:8
    env_file: .env
    ports:
      - "3306:3306"
